### PR TITLE
Mudanças

### PR DESCRIPTION
**Pull request by marianamorais**
Alterei alguns textos e adicionei alguns comandos.

### CODE REVIEW

**Comment by dpaiv0** [comment]
OH CRAP A GRILL

**Comment by joaoesteves10** [comment]
(???)On 3 Mar 2020 11:53, David Paiva <notifications@github.com> wrote:OH CRAP A GRILL

**Comment by dpaiv0** [comment]
yo where you here

**Comment by dpaiv0** [comment]
yo why you here

**Comment by joaoesteves10** [comment]
I'm everywhereOn 3 Mar 2020 12:19, David Paiva <notifications@github.com> wrote:yo why you here

**Comment by joaoesteves10** [comment]
I'm everywhere
(eu tinha respondido pelo e-mail por isso tava com aquilo sksjkrwm)

**Comment by dpaiv0** [comment]
yeah but stop using your email for that pls

**Comment by joaoesteves10** [comment]
:c

**Pull request merged**
